### ISSUE TITLE
No new sets since december 31st

### ISSUE THREAD

**Issue by PabloMansanet** [halvnykterist/strive-ratings#1]
It seems like, despite the [timestamp at the top](https://halvnykterist.github.io/strive-ratings/) claiming data has been retrieved daily, there aren't any new sets from 2022.

Is there anything we can do to help fix this?

Thanks!

**Comment by halvnykterist** [comment]
Sorry, missed that this issue was here. Basically, the import script I'd been using failed sometime around the new year. As I'm sure you know, I changed the way I import things and put a new site up at http://ratingupdate.info/. There's a repo for it at https://github.com/halvnykterist/rating-update.
